"""Cadeias de teste por ER.

aceitas: cadeias que devem casar.
rejeitadas: pares (cadeia, motivo) que não devem casar.
limite: casos-limite, que também aparecem em aceitas ou rejeitadas.
"""

CASOS = {
    "ER01": {
        "aceitas": [
            "METAR SBBE",
            "SPECI SBGR",
            "METAR COR SBBE",
            "METAR SNBR",
            "SPECI COR SWPI",
            "METAR SIZZ",
            "METAR SDAA",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("METAR SABE", "SA é prefixo da Argentina, não do Brasil"),
            ("TAF SBBE", "TAF é previsão, não observação"),
            ("METAR  SBBE", "dois espaços entre os grupos"),
            ("metar SBBE", "letras minúsculas"),
            ("METAR SBB", "indicativo com 3 letras"),
            ("METAR COR", "falta o indicativo do aeródromo"),
            ("METAR SBBEX", "indicativo com 5 letras"),
            ("METARSBBE", "falta o espaço"),
        ],
        "limite": ["METAR SIZZ", "METAR COR SBBE", "METAR  SBBE", ""],
    },
    "ER02": {
        "aceitas": [
            "241200Z",
            "010000Z",
            "312359Z",
            "152330Z",
            "100630Z",
            "290045Z",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("001200Z", "dia 00 não existe"),
            ("321200Z", "dia 32 não existe"),
            ("242400Z", "hora 24 fora de 00–23"),
            ("241260Z", "minuto 60 fora de 00–59"),
            ("241200", "falta o Z (UTC)"),
            ("24120Z", "só 5 dígitos"),
            ("2412000Z", "7 dígitos"),
            ("241200z", "z minúsculo"),
        ],
        "limite": ["010000Z", "312359Z", "242400Z", "241260Z", ""],
    },
    "ER03": {
        "aceitas": [
            "09010KT",
            "00000KT",
            "36015G25KT",
            "VRB03KT",
            "270105KT",
            "18012G120KT",
            "35008KT",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("37010KT", "direção 370° acima de 360"),
            ("09510KT", "direção não termina em 0 (não é dezena de graus)"),
            ("09010", "falta a unidade KT"),
            ("0901KT", "velocidade com 1 dígito"),
            ("36015G5KT", "rajada com 1 dígito"),
            ("09010MPS", "unidade MPS não prevista"),
            ("VRBKT", "falta a velocidade"),
            ("36115KT", "direção 361° não é dezena de graus"),
        ],
        "limite": ["00000KT", "36015G25KT", "270105KT", "36115KT", ""],
    },
    "ER04": {
        "aceitas": [
            "9999",
            "CAVOK",
            "0800",
            "5000NE",
            "0000",
            "3000SW",
            "1500N",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("999", "apenas 3 dígitos"),
            ("99999", "5 dígitos"),
            ("CAVOk", "letra minúscula"),
            ("5000NNE", "direção com 3 letras não prevista"),
            ("5000X", "X não é direção"),
            ("CAVOK9999", "CAVOK e valor numérico juntos"),
            ("KM10", "formato em km não previsto"),
        ],
        "limite": ["0000", "9999", "CAVOK9999", ""],
    },
    "ER05": {
        "aceitas": [
            "RA",
            "-RA",
            "+TSRA",
            "VCSH",
            "BR",
            "TS",
            "-SHRA",
            "FZDZ",
            "RABR",
            "+SHRAGR",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("+", "só a intensidade, sem fenômeno"),
            ("-VC", "duas indicações de intensidade/proximidade"),
            ("XX", "código inexistente"),
            ("RA+", "intensidade depois do fenômeno"),
            ("VCVC", "VC repetido"),
            ("TSTS", "dois descritores"),
            ("ra", "letras minúsculas"),
            ("SHXX", "XX não é fenômeno"),
            ("-+RA", "duas intensidades"),
        ],
        "limite": ["TS", "RABR", "TSTS", "-+RA", ""],
    },
    "ER06": {
        "aceitas": [
            "FEW020",
            "SCT015CB",
            "BKN100TCU",
            "OVC008",
            "VV002",
            "NSC",
            "NCD",
            "FEW000",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("FEW20", "altura com 2 dígitos"),
            ("FEW0200", "altura com 4 dígitos"),
            ("SKC", "código SKC não é usado no Brasil"),
            ("BKN015XB", "XB não é tipo de nuvem"),
            ("OVC", "falta a altura"),
            ("VV02", "visibilidade vertical com 2 dígitos"),
            ("NSCX", "símbolo sobrando depois de NSC"),
            ("FEWCB", "falta a altura antes do tipo"),
        ],
        "limite": ["FEW000", "NSC", "FEW0200", ""],
    },
    "ER07": {
        "aceitas": [
            "30/24",
            "M05/M07",
            "00/M01",
            "09/09",
            "M00/M00",
            "45/30",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("30-24", "separador - no lugar de /"),
            ("3/24", "temperatura com 1 dígito"),
            ("30/", "falta o ponto de orvalho"),
            ("M5/M7", "valores com 1 dígito"),
            ("30//24", "barra repetida"),
            ("MM05/07", "M repetido"),
            ("30/24M", "M depois do valor"),
            ("30/245", "orvalho com 3 dígitos"),
        ],
        "limite": ["M00/M00", "00/M01", "M5/M7", ""],
    },
    "ER08": {
        "aceitas": [
            "Q1013",
            "Q0998",
            "Q0900",
            "Q1099",
            "Q1000",
            "Q0950",
        ],
        "rejeitadas": [
            ("", "cadeia vazia"),
            ("Q101", "só 3 dígitos"),
            ("Q10133", "5 dígitos"),
            ("Q1100", "acima de 1099 hPa"),
            ("Q0899", "abaixo de 0900 hPa"),
            ("A2992", "pressão em polegadas (A) não prevista"),
            ("q1013", "q minúsculo"),
            ("Q 1013", "espaço depois do Q"),
            ("1013", "falta o Q"),
        ],
        "limite": ["Q0900", "Q1099", "Q0899", "Q1100", ""],
    },
}
